Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Controllers/CatalogueBoundedContextController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace PPPDDD.NonDist.UIComp.Controllers
{
    public class CatalogBoundedContextController : Controller
    {
        [ChildActionOnly] // action cannot be rendered as an individual page
        public PartialViewResult ItemInBasket(string productId)
        {
            var product = SalesBoundedContext.ProductFinder.Find(productId);

            /* convention will look for a partial view called:
             * /Views/CatalogBoundedContext/ItemInBasket.cshtml
            */
            return PartialView(product);
        }
    }
}

// This would actually be inside a separate project
namespace PPPDDD.NonDist.UIComp.SalesBoundedContext
{
    public static class ProductFinder
    {
        public static Product Find(string productId)
        {
            // simulate a database lookup
            return new Product
            {
                ID = productId,
                Name = "Product_" + productId,
                Description = "Lorem ipsum dolor sit amet",
                ImageUrl = "http://media.wiley.com/product_data/coverImage/84/04702927/0470292784.jpg"
            };
        }
    }

    public class Product
    {
        public string ID { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string ImageUrl { get; set; }
    }
}

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Controllers/HomeController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace PPPDDD.NonDist.UIComp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Controllers/PricingBoundedContextController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace PPPDDD.NonDist.UIComp.Controllers
{
    public class PricingBoundedContextController : Controller
    {
        [ChildActionOnly] // cannot be rendered as a page
        public PartialViewResult Price(string productId)
        {
            var price = PricingBoundedContext.PriceFinder.PriceFor(productId);

            /* convention will look for a partial view called:
             * /Views/PricingBoundedContext/Price.cshtml
            */
            return PartialView(price);
        }
    }
}

// would actually live in a separate project
namespace PPPDDD.NonDist.UIComp.PricingBoundedContext
{
    public static class PriceFinder
    {
        private static Lazy<Random> random = new Lazy<Random>();

        public static int PriceFor(string productId)
        {
            // simulate a database lookup
            return random.Value.Next(1, 1000);
        }
    }
}

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Controllers/ShippingBoundedContextController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace PPPDDD.NonDist.UIComp.Controllers
{
    public class ShippingBoundedContextController : Controller
    {
        [ChildActionOnly] // cannot be rendered as a page
        public PartialViewResult DeliveryOptions()
        {
            var options = ShippingBoundedContext.DeliveryOptions.All();

            /* convention will look for a partial view called:
            * /Views/ShippingBoundedContext/DeliveryOptions.cshtml
           */
            return PartialView(options);
        }
    }
}

// would actually be in a separate project
namespace PPPDDD.NonDist.UIComp.ShippingBoundedContext
{
    using System.Collections.Generic;

    public static class DeliveryOptions
    {
        public static IEnumerable<DeliveryOption> All()
        {
            // simulate database lookup
            return new List<DeliveryOption>
            {
                new DeliveryOption
                {
                    ID = "ss1",
                    Name = "Cheap & Cheerful",
                    Price = 2,
                    Duration = new Tuple<int,int>(7, 14)
                },
                new DeliveryOption
                {
                    ID = "ss2",
                    Name = "Super Fast",
                    Price = 50,
                    Duration = new Tuple<int,int>(1, 2)
                }
            };
        }
    }

    public class DeliveryOption
    {
        public string ID { get; set; }

        public string Name { get; set; }

        public int Price { get; set; }

        public Tuple<int, int> Duration { get; set; }
    }
}

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Views/CatalogBoundedContext/ItemInBasket.cshtml
@model PPPDDD.NonDist.UIComp.SalesBoundedContext.Product

<div>
    <h3>@Model.Name</h3>
    <p>
        <img height="75" src="@Model.ImageUrl" style="float: left;" />
        @Model.Description
    </p>
</div>

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Views/Home/Index.cshtml
@{
    Layout = null;
    var productIdsInBasket = new string[3] { "prod1", "prod2", "prod3"};
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PPPDDD Composite UI</title>
    @*
        Can also use RenderAction here if Bounded Contexts
        need to inject custom javascript
    *@
</head>
<body>
    <div> 
        <h1>Your Basket</h1>
        @foreach(var pid in productIdsInBasket)
        {
            <div class="basketItem" style="margin-bottom: 20px;">
                @{ Html.RenderAction("ItemInBasket", "CatalogBoundedContext", new { productId = pid}); } 
                @{ Html.RenderAction("Price", "PricingBoundedContext", new { productId = pid }); }
            </div>
            <br />
        }
        @{ Html.RenderAction("DeliveryOptions", "ShippingBoundedContext"); }
    </div>
</body>
</html>

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Views/PricingBoundedContext/Price.cshtml
@model int

<div class="price">
    $@String.Format(Model.ToString(), "##.##")
</div>

Chapter 23/23 - Architecting Application User Interfaces/PPPDDD.NonDist.UIComp/PPPDDD.NonDist.UIComp/Views/ShippingBoundedContext/DeliveryOptions.cshtml
@model IEnumerable<PPPDDD.NonDist.UIComp.ShippingBoundedContext.DeliveryOption>

<div class="deliveryOptions">
    <h2>Delivery Options</h2>
    @foreach(var option in Model)
    {
        <p>
            @Html.RadioButton("deliveryOptions", option.ID)
            @option.Name - $@String.Format(option.Price.ToString(), "##.##")
             (@option.Duration.Item1 - @option.Duration.Item2 days)
        </p>
            
    }
</div>